-- =====================================================================
--  MODUL OPERASIONAL — PLATFORM TERPADU
--
--  Sistem operasional ILJ (Laravel, repo LaporanKeuangan) pindah ke
--  database yang sama dengan portal laporan. Tabel di bawah adalah
--  bentuk AKHIR schema Laravel per 6 Oktober 2026 — hasil seluruh
--  45 migrasinya, bukan salinan migrasi per migrasi — diterjemahkan ke
--  Postgres dengan aturan portal ini.
--
--  Yang sengaja berbeda dari Laravel, dan alasannya:
--
--    - entity_id di SETIAP tabel. Keputusan 7 Oktober 2026: data
--      operasional milik entitas, dan akses mengikuti user_entity_access
--      seperti laporan. Seluruh data lama adalah ILJ.
--    - nominal uang numeric(18,2), bukan decimal(15,2). Invarian 3.
--    - id tetap bigint, bukan uuid, dan `generated by default` — skrip
--      migrasi data menyisipkan id lama apa adanya, sehingga nomor yang
--      sudah tercetak di dokumen tetap menunjuk baris yang sama.
--    - created_by/updated_by menunjuk profiles, bukan users. Akun Laravel
--      tidak dipindah (password bcrypt tidak bisa dibawa ke Neon Auth);
--      direksi membuat ulang akunnya.
--    - activity_logs TIDAK dibuat. Setiap tabel di sini diaudit trigger
--      audit_row() (invarian 4); notifikasi kolaborasi membaca audit_log.
--    - pengeluaran_line_mapping TIDAK dibuat. Sudah tidak dipakai sejak
--      keputusan 4 Oktober 2026; penggantinya operational_expense_mapping.
--    - users, sessions, cache, jobs TIDAK dibuat. Itu infrastruktur
--      Laravel, bukan data.
--
--  Yang sengaja SAMA, meski tidak ideal, supaya data lama masuk tanpa
--  diubah:
--
--    - transaksi_operasional.pendapatan dan kapal_muatan_detail.
--      pendapatan_rekanan menyimpan hasil hitung (tonase x tarif). Itu
--      bukan subtotal laporan laba rugi, jadi tidak melanggar invarian 2,
--      tetapi tetap angka turunan yang bisa basi. Ditinjau saat modulnya
--      di-port — lihat docs/PENGGABUNGAN.md.
--    - kolom `pendapatan` di transaksi_operasional adalah BEBAN rekanan,
--      bukan pendapatan. Namanya dipertahankan; lihat
--      docs/task/10-integrasi-operasional.md.
--    - laporan_pendapatan.tanggal_kegiatan tetap teks. Di Laravel kolom
--      itu string bebas ("12-15 Mei"), bukan tanggal.
-- =====================================================================


-- =====================================================================
--  BAGIAN 1 — HAK AKSES
-- =====================================================================

-- --- 1a. Modul operasional --------------------------------------------
--
--  Baca: direksi dan admin_operasional, pada entitas yang boleh ia
--  lihat. Tulis: admin_operasional saja.
--
--  Direksi tidak menulis. Di Laravel, peran yang membaca tanpa menulis
--  adalah HRD, dan untuk saat ini akun HRD memakai peran direksi —
--  memberi direksi hak tulis akan memberikannya juga ke HRD tanpa ada
--  yang memutuskannya. Daftar izin, bukan daftar larangan: peran baru
--  tidak mendapat apa pun sampai dinyatakan di sini.

create or replace function can_read_operational(target_entity uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(current_user_role() in ('direksi', 'admin_operasional'), false)
     and has_entity_access(target_entity);
$$;

comment on function can_read_operational(uuid) is
  'Boleh membaca data operasional entitas ini: direksi dan admin_operasional.';

create or replace function can_write_operational(target_entity uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(current_user_role() = 'admin_operasional', false)
     and has_entity_access(target_entity);
$$;

comment on function can_write_operational(uuid) is
  'Boleh menulis data operasional entitas ini: admin_operasional yang ditugaskan.';


-- --- 1b. Laporan laba rugi: daftar izin eksplisit ---------------------
--
--  Sampai migrasi ini, periods_insert, periods_update, dan lines_write
--  hanya mensyaratkan "punya akses entitas dan bukan auditor". Itu benar
--  selama setiap peran non-auditor memang peran laporan. admin_operasional
--  bukan: tanpa perubahan ini, admin operasional yang ditugaskan ke ILJ
--  dapat membuat periode P&L ILJ, mengubah angkanya, dan MENGAJUKANNYA —
--  guard_period_transition tidak membatasi siapa yang boleh mengajukan.
--
--  Kedua fungsi mempertahankan hak keempat peran lama persis seperti
--  sebelumnya. Yang berubah hanya: peran yang tidak disebut tidak
--  mendapat apa pun.
--
--  Baca P&L juga dipersempit. Apakah admin operasional boleh membaca
--  laporan laba rugi belum diputuskan; sampai diputuskan, tidak.

create or replace function can_read_reports()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    current_user_role() in ('direksi', 'manajer_keuangan', 'staf_entitas', 'auditor'),
    false
  );
$$;

comment on function can_read_reports() is
  'Peran yang boleh membaca periode dan baris laporan laba rugi. Cakupan entitas tetap has_entity_access().';

create or replace function can_write_reports()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    current_user_role() in ('direksi', 'manajer_keuangan', 'staf_entitas'),
    false
  );
$$;

comment on function can_write_reports() is
  'Peran yang boleh membuat periode dan menulis baris laporan. Pengganti `not is_readonly_role()` di policy laporan.';

drop policy if exists periods_select on periods;
create policy periods_select on periods for select to authenticated
  using (has_entity_access(entity_id) and can_read_reports());

drop policy if exists periods_insert on periods;
create policy periods_insert on periods for insert to authenticated
  with check (has_entity_access(entity_id) and can_write_reports());

drop policy if exists periods_update on periods;
create policy periods_update on periods for update to authenticated
  using (has_entity_access(entity_id) and can_write_reports())
  with check (has_entity_access(entity_id) and can_write_reports());

drop policy if exists lines_select on report_lines;
create policy lines_select on report_lines for select to authenticated
  using (
    can_read_reports()
    and exists (
      select 1 from periods p
      where p.id = report_lines.period_id
        and has_entity_access(p.entity_id)
    )
  );

drop policy if exists lines_write on report_lines;
create policy lines_write on report_lines for all to authenticated
  using (
    can_write_reports()
    and exists (
      select 1 from periods p
      where p.id = report_lines.period_id
        and has_entity_access(p.entity_id)
        and p.status = 'draft'
    )
  )
  with check (
    can_write_reports()
    and exists (
      select 1 from periods p
      where p.id = report_lines.period_id
        and has_entity_access(p.entity_id)
        and p.status = 'draft'
    )
  );


-- =====================================================================
--  BAGIAN 2 — MASTER DATA
-- =====================================================================

create table pemilik (
  id            bigint generated by default as identity primary key,
  entity_id     uuid not null references entities(id) on delete restrict,
  nama_pemilik  text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table pemilik is 'Pemilik kendaraan (rekanan). Laravel: pemilik.';

create table kapal (
  id                 bigint generated by default as identity primary key,
  entity_id          uuid not null references entities(id) on delete restrict,
  nama_kapal         text not null,             -- tidak unik: kapal yang sama datang lagi bulan lain
  nama_paguyuban     text,
  bulan              smallint check (bulan between 1 and 12),
  voyage             text,
  pemilik_kapal      text,
  tahun_pembuatan    smallint,
  kapasitas_ton      numeric(10,2),
  tarif_tonase       numeric(18,2) not null default 0,
  biaya_operasional  numeric(18,2) not null default 0,
  status             text not null default 'aktif' check (status in ('aktif', 'nonaktif')),
  keterangan         text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

comment on table kapal is
  'Satu kedatangan/kegiatan kapal, bukan satu kapal fisik — nama_kapal sengaja tidak unik. Laravel: kapal.';

create table karyawan (
  id                 bigint generated by default as identity primary key,
  entity_id          uuid not null references entities(id) on delete restrict,
  nama               text not null,
  no_hp              text,
  alamat             text,
  tanggal_bergabung  date,
  status             text not null default 'aktif' check (status in ('aktif', 'nonaktif')),
  jabatan            text,
  ktp                text,
  npwp               text,
  tarif_telly        numeric(18,2) not null default 0,
  pph_persen         numeric(5,2) not null default 0,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create table karyawan_catatan (
  id           bigint generated by default as identity primary key,
  entity_id    uuid not null references entities(id) on delete restrict,
  karyawan_id  bigint not null references karyawan(id) on delete cascade,
  tanggal      date not null,
  jenis        text not null default 'catatan' check (jenis in ('catatan', 'SP1', 'SP2', 'SP3')),
  keterangan   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table kendaraan (
  id          bigint generated by default as identity primary key,
  entity_id   uuid not null references entities(id) on delete restrict,
  nopol       text not null,
  pemilik_id  bigint not null references pemilik(id) on delete cascade,
  npwp        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- Di Laravel unik global. Per entitas di sini: satu truk bisa saja
  -- disewa dua entitas grup.
  unique (entity_id, nopol)
);


-- =====================================================================
--  BAGIAN 3 — KEGIATAN KAPAL
-- =====================================================================

create table kapal_rute (
  id                 bigint generated by default as identity primary key,
  entity_id          uuid not null references entities(id) on delete restrict,
  kapal_id           bigint not null references kapal(id) on delete cascade,
  asal               text not null,             -- Gudang Veteran / KIG / Manyar / Pabrik Wilmar / ...
  tujuan             text not null default 'Kapal/Pelabuhan',
  tonase_mt          numeric(12,2) not null default 0,
  biaya_operasional  numeric(18,2) not null default 0,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create table kapal_muatan_detail (
  id                  bigint generated by default as identity primary key,
  entity_id           uuid not null references entities(id) on delete restrict,
  kapal_id            bigint not null references kapal(id) on delete cascade,
  kendaraan_id        bigint not null references kendaraan(id) on delete cascade,
  kapal_rute_id       bigint references kapal_rute(id) on delete set null,
  ritase              integer not null default 1,
  tonase              numeric(12,2) not null default 0,
  uang_saku_sopir     numeric(18,2) not null default 0,
  uang_terpal         numeric(18,2) not null default 0,
  biaya_rekanan       numeric(18,2) not null default 0,
  pendapatan_rekanan  numeric(18,2) not null default 0,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table kapal_muatan_detail is 'Realisasi muatan per truk per kapal. Laravel: kapal_muatan_detail.';


-- =====================================================================
--  BAGIAN 4 — OPERASIONAL HARIAN & REKAP
-- =====================================================================

create table operasional_rekap (
  id                bigint generated by default as identity primary key,
  entity_id         uuid not null references entities(id) on delete restrict,
  bulan             smallint not null check (bulan between 1 and 12),
  tahun             smallint not null,
  kapal_id          bigint not null references kapal(id) on delete cascade,
  rute              text,
  trips             integer,
  tonase            numeric(12,2),
  sangu_supir       numeric(18,2),
  terpal            numeric(18,2),
  operasional       numeric(18,2) not null default 0,
  telly_id          bigint references karyawan(id) on delete set null,
  tanggal_input     date,
  tanggal_kegiatan  date,
  tanggal_selesai   date,
  keterangan        text,
  created_by        uuid references profiles(id) on delete set null,
  updated_by        uuid references profiles(id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table operasional_rekap is
  'Rekap manual per (bulan, tahun, kapal, rute). Sumber COGS_OPS — lihat docs/task/10-integrasi-operasional.md.';

create table transaksi_operasional (
  id                      bigint generated by default as identity primary key,
  entity_id               uuid not null references entities(id) on delete restrict,

  -- Bulan sebuah transaksi ditentukan oleh `tanggal`, bukan
  -- tanggal_kegiatan atau tanggal_selesai. Lihat 10-integrasi-operasional.md.
  tanggal                 date not null,
  tanggal_kegiatan        date,
  tanggal_selesai         date,
  tanggal_input           date,

  kapal_id                bigint not null references kapal(id) on delete cascade,
  operasional_rekap_id    bigint references operasional_rekap(id) on delete cascade,
  kendaraan_id            bigint references kendaraan(id) on delete cascade,
  kapal_muatan_detail_id  bigint references kapal_muatan_detail(id) on delete set null,

  rute                    text not null,
  ritase                  integer not null default 1,
  tonase                  numeric(12,2) not null default 0,
  ongkos_angkut           numeric(18,2) not null default 0,

  -- BEBAN rekanan (tonase x ongkos_angkut), bukan pendapatan ILJ.
  pendapatan              numeric(18,2) not null default 0,

  sangu_supir             numeric(18,2) not null default 0,
  terpal                  numeric(18,2) not null default 0,

  -- Selalu 0 sejak migrasi Laravel 2026_04_06_000900. Biaya operasional
  -- yang sebenarnya ada di operasional_rekap.operasional.
  operasional             numeric(18,2) not null default 0,

  telly_id                bigint references karyawan(id) on delete set null,
  keterangan              text,

  created_by              uuid references profiles(id) on delete set null,
  updated_by              uuid references profiles(id) on delete set null,
  version                 integer not null default 1,

  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

comment on column transaksi_operasional.pendapatan is
  'Beban rekanan: tonase x ongkos_angkut, dibayarkan ke pemilik truk. Bukan pendapatan ILJ.';

create table gaji_telly (
  id                    bigint generated by default as identity primary key,
  entity_id             uuid not null references entities(id) on delete restrict,
  karyawan_id           bigint not null references karyawan(id) on delete cascade,

  -- Tiga jenis baris, lihat 10-integrasi-operasional.md:
  --   transaksi_id terisi          upah telly per kegiatan
  --   operasional_rekap_id terisi  upah telly per rekap
  --   keduanya null                gaji admin bulanan (bulan dari created_at)
  transaksi_id          bigint references transaksi_operasional(id) on delete cascade,
  operasional_rekap_id  bigint references operasional_rekap(id) on delete set null,

  gaji                  numeric(18,2) not null default 0,
  gaji_total            numeric(18,2) not null default 0,
  pph                   numeric(18,2) not null default 0,
  gaji_bersih           numeric(18,2) not null default 0,
  keterangan            text,

  -- Untuk gaji admin, created_at adalah PENANDA BULAN, bukan waktu
  -- pembuatan. Skrip migrasi data menyalinnya apa adanya.
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create table paguyuban (
  id            bigint generated by default as identity primary key,
  entity_id     uuid not null references entities(id) on delete restrict,
  transaksi_id  bigint not null unique references transaksi_operasional(id) on delete cascade,
  tanggal       date not null,
  jumlah_orang  integer,
  tarif         numeric(18,2) not null default 500,
  total_bayar   numeric(18,2) not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table pengeluaran (
  id             bigint generated by default as identity primary key,
  entity_id      uuid not null references entities(id) on delete restrict,
  tanggal        date not null,

  -- Teks bebas; dipetakan ke pos laporan lewat operational_expense_mapping.
  jenis          text not null,

  nama_kegiatan  text,
  jumlah         numeric(18,2) not null,
  penerima       text,
  keterangan     text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);


-- =====================================================================
--  BAGIAN 5 — PENCAIRAN & PENDAPATAN
-- =====================================================================

create table pencairan (
  id               bigint generated by default as identity primary key,
  entity_id        uuid not null references entities(id) on delete restrict,
  kapal_id         bigint not null references kapal(id) on delete cascade,
  bulan            smallint not null check (bulan between 1 and 12),
  nomor_invoice    text not null,
  nominal_invoice  numeric(18,2) not null,
  besaran_pajak    numeric(18,2) not null default 0,
  status           text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  unique (entity_id, nomor_invoice)
);

create table pencairan_approval (
  id            bigint generated by default as identity primary key,
  entity_id     uuid not null references entities(id) on delete restrict,
  pencairan_id  bigint not null references pencairan(id) on delete cascade,
  departemen    text not null check (departemen in ('Jetty', 'Gudang', 'Accounting')),
  status        text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  tanggal_ttd   date,
  keterangan    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  unique (pencairan_id, departemen)
);

create table laporan_pendapatan (
  id                bigint generated by default as identity primary key,
  entity_id         uuid not null references entities(id) on delete restrict,
  bulan             smallint not null check (bulan between 1 and 12),
  tahun             smallint not null,
  no_urut           integer,
  no_invoice        text,
  kegiatan          text not null,
  no_faktur_pajak   text,
  no_sto_spo        text,
  lokasi            text,
  tanggal_kegiatan  text,                       -- teks bebas, lihat kepala berkas
  party_kg          numeric(15,2) not null default 0,
  harga             numeric(18,2) not null default 0,
  total             numeric(18,2) not null default 0,
  tarif_pajak       numeric(5,2) not null default 0.50,
  pajak             numeric(18,2) not null default 0,
  net_tagihan       numeric(18,2) not null default 0,
  status_entry      text,
  tanggal_entry     date,
  payment_date      date,
  keterangan        text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table laporan_pendapatan is
  'Invoice ke pelanggan per bulan. Sumber REV_TAGIHAN (total) dan COGS_PAJAK (pajak).';

create table laporan_kumpulan (
  id            bigint generated by default as identity primary key,
  entity_id     uuid not null references entities(id) on delete restrict,
  bulan         smallint not null check (bulan between 1 and 12),
  tahun         smallint not null,
  cards_json    jsonb,
  summary_json  jsonb,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  unique (entity_id, bulan, tahun)
);


-- =====================================================================
--  BAGIAN 6 — INDEKS
--
--  Postgres tidak membuat indeks untuk foreign key secara otomatis,
--  berbeda dari MySQL/InnoDB. Tanpa ini setiap penghapusan kapal
--  memindai seluruh tabel anaknya.
-- =====================================================================

create index pemilik_entity_idx               on pemilik (entity_id);
create index kapal_entity_idx                 on kapal (entity_id);
create index karyawan_entity_idx              on karyawan (entity_id);
create index karyawan_catatan_karyawan_idx    on karyawan_catatan (karyawan_id);
create index kendaraan_pemilik_idx            on kendaraan (pemilik_id);
create index kapal_rute_kapal_idx             on kapal_rute (kapal_id);
create index muatan_kapal_idx                 on kapal_muatan_detail (kapal_id);
create index muatan_kendaraan_idx             on kapal_muatan_detail (kendaraan_id);
create index muatan_rute_idx                  on kapal_muatan_detail (kapal_rute_id);
create index rekap_entity_periode_idx         on operasional_rekap (entity_id, tahun, bulan);
create index rekap_kapal_idx                  on operasional_rekap (kapal_id);
create index transaksi_entity_tanggal_idx     on transaksi_operasional (entity_id, tanggal);
create index transaksi_kapal_idx              on transaksi_operasional (kapal_id);
create index transaksi_rekap_idx              on transaksi_operasional (operasional_rekap_id);
create index transaksi_kendaraan_idx          on transaksi_operasional (kendaraan_id);
create index transaksi_muatan_idx             on transaksi_operasional (kapal_muatan_detail_id);
create index transaksi_telly_idx              on transaksi_operasional (telly_id);
create index gaji_telly_karyawan_idx          on gaji_telly (karyawan_id);
create index gaji_telly_transaksi_idx         on gaji_telly (transaksi_id);
create index gaji_telly_rekap_idx             on gaji_telly (operasional_rekap_id);
create index pengeluaran_entity_tanggal_idx   on pengeluaran (entity_id, tanggal);
create index pencairan_kapal_idx              on pencairan (kapal_id);
create index pencairan_approval_pencairan_idx on pencairan_approval (pencairan_id);
create index pendapatan_entity_periode_idx    on laporan_pendapatan (entity_id, tahun, bulan);


-- =====================================================================
--  BAGIAN 7 — PELAKU PERUBAHAN
--
--  created_by dan updated_by diisi database dari sesi, tidak dipercaya
--  dari klien — pola yang sama dengan guard_period_insert. Sesi tanpa
--  auth.uid() (skrip migrasi data) mempertahankan nilai yang dikirim.
-- =====================================================================

create or replace function stamp_operational_actor()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := coalesce(auth.uid(), new.created_by);
  else
    new.created_by := old.created_by;
  end if;
  new.updated_by := coalesce(auth.uid(), new.updated_by);
  return new;
end;
$$;

create trigger transaksi_operasional_actor before insert or update on transaksi_operasional
  for each row execute function stamp_operational_actor();
create trigger operasional_rekap_actor before insert or update on operasional_rekap
  for each row execute function stamp_operational_actor();


-- =====================================================================
--  BAGIAN 8 — TRIGGER BAKU, RLS, DAN GRANT
--
--  Setiap tabel operasional mendapat perlakuan yang persis sama, jadi
--  ditulis sekali dalam satu loop. Daftar tabelnya ada di satu tempat;
--  tabel operasional baru yang tidak ditambahkan ke daftar ini tidak
--  punya RLS — dan tests/operasional-rls.test.ts akan gagal.
--
--    updated_at  set_updated_at()
--    audit       audit_row()                         invarian 4
--    RLS         baca can_read_operational()         invarian 1
--                tulis can_write_operational()
--    grant       seluas policy-nya; 'anon' tidak mendapat apa pun
-- =====================================================================

do $$
declare
  t text;
begin
  foreach t in array array[
    'pemilik', 'kapal', 'karyawan', 'karyawan_catatan', 'kendaraan',
    'kapal_rute', 'kapal_muatan_detail', 'operasional_rekap',
    'transaksi_operasional', 'gaji_telly', 'paguyuban', 'pengeluaran',
    'pencairan', 'pencairan_approval', 'laporan_pendapatan', 'laporan_kumpulan'
  ]
  loop
    execute format(
      'create trigger %1$s_updated_at before update on %1$I
         for each row execute function set_updated_at()', t);

    execute format(
      'create trigger audit_%1$s after insert or update or delete on %1$I
         for each row execute function audit_row()', t);

    execute format('alter table %I enable row level security', t);

    execute format(
      'create policy %1$s_select on %1$I for select to authenticated
         using (can_read_operational(entity_id))', t);

    execute format(
      'create policy %1$s_write on %1$I for all to authenticated
         using (can_write_operational(entity_id))
         with check (can_write_operational(entity_id))', t);

    execute format(
      'grant select, insert, update, delete on %I to authenticated', t);
  end loop;
end;
$$;
